// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVg05CS2n7wXQPvvha4D7RXcI0NaYgFU',
    appId: '1:147832977393:web:c3f4c9b014dc55919b7650',
    messagingSenderId: '147832977393',
    projectId: 'barmejapp',
    authDomain: 'barmejapp.firebaseapp.com',
    storageBucket: 'barmejapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUduIbK70aoq93hbyrxTwfduHfns5x8js',
    appId: '1:147832977393:android:376dbbd5de492cf59b7650',
    messagingSenderId: '147832977393',
    projectId: 'barmejapp',
    storageBucket: 'barmejapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLn56cT9d7r2ymFUQtqRpiRgIzIUlD1Uc',
    appId: '1:147832977393:ios:7b27d97843986db59b7650',
    messagingSenderId: '147832977393',
    projectId: 'barmejapp',
    storageBucket: 'barmejapp.appspot.com',
    iosBundleId: 'com.example.brmgApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLn56cT9d7r2ymFUQtqRpiRgIzIUlD1Uc',
    appId: '1:147832977393:ios:89fa3d0fd58b6dbc9b7650',
    messagingSenderId: '147832977393',
    projectId: 'barmejapp',
    storageBucket: 'barmejapp.appspot.com',
    iosBundleId: 'com.example.brmgApplication.RunnerTests',
  );
}
